on: [push]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the docset
      run: |
        echo `python3 --version`
        sudo apt-get install python3-sphinx
        sudo apt-get install -y python3-setuptools
        pip3 install wheel
        pip3 install torch torchvision torchaudio
        cd docs
        pip3 install -r requirements.txt
        pwd
        make html
      id: build     
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: _build/html # The folder the action should deploy. 
